### ISSUE TITLE
Installing chromVAR

### ISSUE THREAD

**Issue by Funshope** [GreenleafLab/chromVAR#20]
I've been having problems installing chromVAR. Below is the output that I'm getting.
Any idea on how I can install it????

BiocInstaller::biocLite("GreenleafLab/chromVAR")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.1 (2017-06-30).
Installing github package(s) ‘GreenleafLab/chromVAR’
Downloading GitHub repo GreenleafLab/chromVAR@master
from URL https://api.github.com/repos/GreenleafLab/chromVAR/zipball/master
Installing chromVAR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/s_/0_w3y8k54336fm35p1dh6ms40000gn/T/Rtmpvl8fj8/devtools7ce6978bc5/GreenleafLab-chromVAR-7f1d5dc'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘chromVAR’ ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c pwm_similarity.cpp -o pwm_similarity.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c utils.cpp -o utils.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o chromVAR.so RcppExports.o pwm_similarity.o utils.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [chromVAR.so] Error 1
ERROR: compilation failed for package ‘chromVAR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/chromVAR’
Installation failed: Command failed (1)

**Comment by AliciaSchep** [comment]
I think this might be similar to issue #11, perhaps try out the recommendations Caleb suggested there?

**Comment by Funshope** [comment]
Yes, I'm on MAC.

**Comment by Funshope** [comment]
Hi Alicia,
I'm still struggling to install chromVAR, Below is the error message I'm still getting
BiocInstaller::biocLite("GreenleafLab/chromVAR")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.1 (2017-06-30).
Installing github package(s) ‘GreenleafLab/chromVAR’
Downloading GitHub repo GreenleafLab/chromVAR@master
from URL https://api.github.com/repos/GreenleafLab/chromVAR/zipball/master
Installing chromVAR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/s_/0_w3y8k54336fm35p1dh6ms40000gn/T/RtmpT4m9IK/devtoolsc1e40168a60/GreenleafLab-chromVAR-7f1d5dc'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘chromVAR’ ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c pwm_similarity.cpp -o pwm_similarity.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c utils.cpp -o utils.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o chromVAR.so RcppExports.o pwm_similarity.o utils.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lquadmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [chromVAR.so] Error 1
ERROR: compilation failed for package ‘chromVAR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/chromVAR’
Installation failed: Command failed (1)

**Comment by caleblareau** [comment]
@Funshope You need the correct version of gfortran installed; see here: http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/

**Comment by Funshope** [comment]
I have installed gfortran, I'm still finding it difficult to instal ChromVAR. Below is the error message I'm getting
The downloaded binary packages are in
	/var/folders/s_/0_w3y8k54336fm35p1dh6ms40000gn/T//RtmpQ7HviA/downloaded_packages
> BiocInstaller::biocLite("GreenleafLab/chromVAR")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.1 (2017-06-30).
Installing github package(s) ‘GreenleafLab/chromVAR’
Downloading GitHub repo GreenleafLab/chromVAR@master
from URL https://api.github.com/repos/GreenleafLab/chromVAR/zipball/master
Installing chromVAR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/s_/0_w3y8k54336fm35p1dh6ms40000gn/T/RtmpQ7HviA/devtools24030afe234/GreenleafLab-chromVAR-7f1d5dc'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘chromVAR’ ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c pwm_similarity.cpp -o pwm_similarity.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c utils.cpp -o utils.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o chromVAR.so RcppExports.o pwm_similarity.o utils.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin16/6.3.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/chromVAR/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘GO.db’
ERROR: lazy loading failed for package ‘chromVAR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/chromVAR’
Installation failed: Command failed (1)

**Comment by caleblareau** [comment]
@Funshope you're super close! I think that the Cpp code is compiling now; there's a pesky dependency (`GO.db`) that doesn't automatically install (https://github.com/GreenleafLab/chromVAR/issues/17 ) 

Try this in `R`:

```
source("https://bioconductor.org/biocLite.R")
biocLite("GO.db")
devtools::install_github("GreenleafLab/chromVAR")
```

**Comment by jaychung10010** [comment]
Hi everyone,
I've also been having problems compiling chromVar. I'm using Mac OS 10.11 with R3.4.1 (both recent update). I've tried all previous suggestions but this problem still persists:

Would appreciate any help!

> BiocInstaller::biocLite("GreenleafLab/chromVAR")

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.1 (2017-06-30).
Installing github package(s) ‘GreenleafLab/chromVAR’
Downloading GitHub repo GreenleafLab/chromVAR@master
from URL https://api.github.com/repos/GreenleafLab/chromVAR/zipball/master
Installing chromVAR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/zk/sr7pyb897114ybyjclrgq_jh0000gp/T/RtmpZWVPp8/devtools2ef62a89a91/GreenleafLab-chromVAR-31c31f9'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘chromVAR’ ...
** libs
2017-09-29 16:35:34.230 xcodebuild[770:21659] Error loading /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/iPhoneOS Build System Support.xcplugin/Contents/MacOS/iPhoneOS Build System Support:  dlopen(/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/iPhoneOS Build System Support.xcplugin/Contents/MacOS/iPhoneOS Build System Support, 265): Library not loaded: /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/DTDeviceKitBase.framework/Versions/A/DTDeviceKitBase
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice: GC capability mismatch
2017-09-29 16:35:34.231 xcodebuild[770:21659] WARNING: Failed to load plugin at: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/iPhoneOS Build System Support.xcplugin, skipping.  Could not load bundle.
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
2017-09-29 16:35:34.584 xcodebuild[772:21681] Error loading /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/iPhoneOS Build System Support.xcplugin/Contents/MacOS/iPhoneOS Build System Support:  dlopen(/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/iPhoneOS Build System Support.xcplugin/Contents/MacOS/iPhoneOS Build System Support, 265): Library not loaded: /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/PrivateFrameworks/DTDeviceKitBase.framework/Versions/A/DTDeviceKitBase
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice: GC capability mismatch
2017-09-29 16:35:34.585 xcodebuild[772:21681] WARNING: Failed to load plugin at: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/PrivatePlugIns/iPhoneOS Build System Support.xcplugin, skipping.  Could not load bundle.
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include/RcppArmadillo.h:34:
In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include/Rcpp.h:72:
In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include/Rcpp/sugar/sugar.h:31:
In file included from /Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include/Rcpp/sugar/functions/functions.h:42:
/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include/Rcpp/sugar/functions/sapply.h:26:11: fatal error: 'type_traits' file not found
        #include <type_traits> // ::std::result_of
                 ^
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘chromVAR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/chromVAR’
Installation failed: Command failed (1)

**Comment by cajanegra1** [comment]
Hi guys,
Maybe the problem I experienced was similar to some of the issues people report in this thread, or it might have been a totally different bug, but I'll report it anyhow since it might help other users. It's quite simple. I'm trying to install chromVAR on an Amazon Ubuntu instance. Installation runs like a breeze with R 3.3.0, but it fails with R 3.3.3. Specifically, it gets clogged trying to install TFBSTools. No need to answer to this post since I'm happy to work with R 3.3.0, but just wanted to make you guys aware of this potential compatibility issue.

**Comment by yingyonghui** [comment]
> I think this might be similar to issue #11, perhaps try out the recommendations Caleb suggested there?
> 
> Edit: Are you on a Mac? Can you specify the OS?

Hi @AliciaSchep , I'm trying to install chromVar in an Ubuntu 18.04 platform with R 3.6.0, and I encountered the same problem mentioned above. Here is the error output. 
Any suggestions would be appreciated!

* installing *source* package ‘chromVAR’ ...
** using staged installation
** libs
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/luh/.conda/envs/seurat3/lib/R/include" -DNDEBUG  -I"/home/luh/.conda/envs/seurat3/lib/R/library/Rcpp/include" -I"/home/luh/.conda/envs/seurat3/lib/R/library/RcppArmadillo/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/luh/.conda/envs/seurat3/include -Wl,-rpath-link,/home/luh/.conda/envs/seurat3/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/luh/.conda/envs/seurat3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1562872960081/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/luh/.conda/envs/seurat3=/usr/local/src/conda-prefix  -c RcppExports.cpp -o RcppExports.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/luh/.conda/envs/seurat3/lib/R/include" -DNDEBUG  -I"/home/luh/.conda/envs/seurat3/lib/R/library/Rcpp/include" -I"/home/luh/.conda/envs/seurat3/lib/R/library/RcppArmadillo/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/luh/.conda/envs/seurat3/include -Wl,-rpath-link,/home/luh/.conda/envs/seurat3/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/luh/.conda/envs/seurat3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1562872960081/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/luh/.conda/envs/seurat3=/usr/local/src/conda-prefix  -c pwm_similarity.cpp -o pwm_similarity.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -I"/home/luh/.conda/envs/seurat3/lib/R/include" -DNDEBUG  -I"/home/luh/.conda/envs/seurat3/lib/R/library/Rcpp/include" -I"/home/luh/.conda/envs/seurat3/lib/R/library/RcppArmadillo/include" -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -I/home/luh/.conda/envs/seurat3/include -Wl,-rpath-link,/home/luh/.conda/envs/seurat3/lib  -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I/home/luh/.conda/envs/seurat3/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base_1562872960081/work=/usr/local/src/conda/r-base-3.6.1 -fdebug-prefix-map=/home/luh/.conda/envs/seurat3=/usr/local/src/conda-prefix  -c utils.cpp -o utils.o
x86_64-conda_cos6-linux-gnu-c++ -std=gnu++11 -shared -L/home/luh/.conda/envs/seurat3/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/luh/.conda/envs/seurat3/lib -Wl,-rpath-link,/home/luh/.conda/envs/seurat3/lib -L/home/luh/.conda/envs/seurat3/lib -Wl,-rpath-link,/home/luh/.conda/envs/seurat3/lib -o chromVAR.so RcppExports.o pwm_similarity.o utils.o -llapack -lblas -lgfortran -lm -lgomp -lquadmath -lpthread -L/home/luh/.conda/envs/seurat3/lib/R/lib -lR
/home/luh/.conda/envs/seurat3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -llapack
/home/luh/.conda/envs/seurat3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make: *** [/home/luh/.conda/envs/seurat3/lib/R/share/make/shlib.mk:6: chromVAR.so] Error 1
ERROR: compilation failed for package ‘chromVAR’
* removing ‘/home/luh/.conda/envs/seurat3/lib/R/library/chromVAR’
